 prefix lwm: <http://lwm.gm.fh-koeln.de/>

 select (count(?notPassed) as ?count) where {
   {
   ### not passed dates
     select ?notPassed where {
        ?student lwm:hasScheduleAssociation ?association .
        ?association lwm:hasGroup ?group .
        ?association lwm:hasAssignmentDate ?date .

        optional{?association lwm:hasPassed ?notPassed} .
        filter(?date < "2014-12-19") .
        filter(?notPassed = "false") .
        filter not exists {?association lwm:hasAlternateScheduleAssociation ?alternate } .
      }
   } union {
   ### Alternate dates that are not passed
     select ?notPassed where {
            ?student lwm:hasScheduleAssociation ?association .
            ?association lwm:hasGroup ?group .
            ?association lwm:hasAssignmentDate ?date .
            optional{?association lwm:hasPassed ?notPassed} .
            optional {
               ?association lwm:hasAlternateScheduleAssociation ?alternate .
               ?alternate lwm:hasAssignmentDate ?alternatedate .
            } .
            filter(?notPassed = "false") .
            filter exists {
               ?association lwm:hasAlternateScheduleAssociation ?alternate .
               ?alternate lwm:hasAssignmentDate ?alternatedate .
            } .
            filter(?alternatedate < "2014-12-19") .
     }
     }
   }
